#!/usr/bin/env sh
#
# https://www.youtube.com/watch?v=dp28SjGoGyo

fuckies="$HOME/.fuckies"
test ! -d "$fuckies" && mkdir "$fuckies"

wuckies="$fuckies/$(date +%F)"
test ! -f "$wuckies" && touch "$wuckies"

oopsie="$@"
test ! -z "$oopsie" && echo "$oopsie" >> "$wuckies"

woopsies="$(wc -l < "$wuckies" | cut -d' ' -f1)"
if [ "$woopsies" -eq 0 ]; then
    echo "(≧∇≦)/: Rawr X3 *nuzzles* OwO what is this? no oopsie woopsies? *pounces on you*"
elif [ "$woopsies" -lt 5 ]; then
    echo "(ᗒᗩᗕ): Youwu awweady made $woopsies fucko boingos?"
else
    echo "(ू˃̣̣̣̣̣̣︿˂̣̣̣̣̣̣ ू): Ouw code monkeys awe wowking vewy hawd to fix your $woopsies fucky wuckies! I can't b-bewieve you wouwd do this to them!"
fi

